version: 0.2
phases:
  pre_build:
    commands:
      - echo we are on pre-build stage.
  build:
    commands:
      - echo we are on build stage.
      - mvn clean
  post_build:
    commands:
      - echo we are on post-build stage.
      - echo packaging war file
      - mvn package
      - echo moving war file from target to root directory.
      - mv target/ofg-api-discovery-ms-1.0.0.war ofg-api-discovery-ms-1.0.0.war
      - echo war moved successfully.
artifacts:
  files:
    - ofg-api-discovery-ms-1.0.0.war
